blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Website
    url: https://projectelixiros.com
    about: Do checkout our website.
  - name: ğŸ’¬ Telegram Support
    url: https://telegram.me/Elixir_Discussion
    about: Join the support chat on telegram.

